starter:
  enabled: true

url:
    locations: https://kudago.com/public-api/v1.4/locations/
    categories: https://kudago.com/public-api/v1.2/place-categories/

executor:
  thread_count: 5
  period: 60