input {
 file {
   mode => "tail"
   path => "/usr/share/logstash/ingest_data/*"
   start_position => "beginning"
   sincedb_path => "/dev/null"
 }
}

output {
 elasticsearch {
   index => "logstash-%{+YYYY.MM.dd}"
   hosts=> "${ELASTIC_HOSTS}"
   user=> "${ELASTIC_USER}"
   password=> "${ELASTIC_PASSWORD}"
   cacert=> "certs/ca/ca.crt"
 }
}

